# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-11 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название направления')),
                ('image', models.CharField(default='http://placehold.it/500x500', max_length=100, verbose_name='Ссылка на картинку')),
                ('date', models.DateField()),
                ('text', models.TextField(verbose_name='Описание курса')),
            ],
            options={
                'db_table': 'directions',
                'verbose_name': 'Направление',
                'verbose_name_plural': 'Направления',
            },
        ),
    ]
