# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-11 20:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('landpage', '0009_auto_20160912_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='lector',
            name='image',
            field=models.CharField(default='http://placehold.it/250x250', max_length=100, verbose_name='Ссылка на картинку'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2016, 9, 11, 20, 26, 42, 304369, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lector',
            name='rang',
            field=models.TextField(verbose_name='Должность'),
        ),
    ]
