# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-11 20:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('landpage', '0011_auto_20160912_0130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название фирмы-клиента')),
                ('ref', models.CharField(default='/', max_length=50, verbose_name='Ссылка на сайт фирмы-клиента')),
            ],
            options={
                'db_table': 'clients',
                'verbose_name_plural': 'Клиенты',
                'verbose_name': 'Клиент',
            },
        ),
        migrations.AlterField(
            model_name='direction',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2016, 9, 11, 20, 43, 47, 815399, tzinfo=utc)),
        ),
    ]
