# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-11 20:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('landpage', '0012_auto_20160912_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='image',
            field=models.CharField(default='http://placehold.it/200x50', max_length=100, verbose_name='Ссылка на лого фирмы-клиента'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2016, 9, 11, 20, 48, 2, 821180, tzinfo=utc)),
        ),
    ]
