# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-11 23:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('landpage', '0013_auto_20160912_0148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('image', models.CharField(default='http://placehold.it/64x64', max_length=100, verbose_name='Иконка')),
                ('text', models.TextField(verbose_name='Текст заголовка')),
            ],
            options={
                'verbose_name_plural': 'Заголовки',
                'verbose_name': 'Заголовок',
                'db_table': 'headers',
            },
        ),
        migrations.AddField(
            model_name='direction',
            name='ref_video',
            field=models.CharField(default='https://youtube.com/', max_length=100, verbose_name='Ссылка на видео на youtube.com'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2016, 9, 11, 23, 3, 46, 875159, tzinfo=utc)),
        ),
    ]
