# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-11 23:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('landpage', '0016_auto_20160912_0413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='header',
            old_name='title',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='direction',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2016, 9, 11, 23, 15, 37, 446401, tzinfo=utc)),
        ),
    ]
