# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-12 00:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('landpage', '0019_auto_20160912_0457'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('text', models.TextField()),
                ('phone', models.CharField(default='+7(347)-xxx-xxx', max_length=20, verbose_name='Телефоны для контактов')),
                ('adres', models.CharField(max_length=140, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'О компании',
                'db_table': 'about',
            },
        ),
        migrations.AlterField(
            model_name='direction',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2016, 9, 12, 0, 6, 48, 47675, tzinfo=utc)),
        ),
    ]
