# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-12 15:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('landpage', '0021_auto_20160912_0511'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Описание докумета')),
                ('imp', models.CharField(choices=[('Лицензия', 'Лицензия'), ('Свидетельство', 'Свидетельство'), ('Аттестат', 'Аттестат'), ('Свидетельство', 'Сертификат')], max_length=20, verbose_name='Тип документа')),
            ],
            options={
                'db_table': 'licence',
                'verbose_name_plural': 'Разрешительные документы',
                'verbose_name': 'Разрещительный документ',
            },
        ),
        migrations.AlterField(
            model_name='direction',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2016, 9, 12, 15, 10, 33, 391177, tzinfo=utc)),
        ),
    ]
