# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-12 15:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('landpage', '0026_auto_20160912_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approve',
            name='imp',
            field=models.CharField(choices=[('Лицензии', 'Лицензии'), ('Свидетельства', 'Свидетельства'), ('Аттестаты', 'Аттестаты'), ('Свидетельства', 'Сертификаты')], max_length=20, verbose_name='Тип документа'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2016, 9, 12, 15, 38, 23, 832618, tzinfo=utc)),
        ),
    ]
