# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-12 16:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('landpage', '0027_auto_20160912_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2016, 9, 12, 16, 7, 58, 216420, tzinfo=utc)),
        ),
    ]
