# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-12 18:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('landpage', '0029_auto_20160912_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=30, verbose_name='Заголовок')),
                ('news_text', models.TextField(verbose_name='Текст новости')),
                ('news_date', models.DateTimeField(verbose_name=datetime.datetime(2016, 9, 12, 18, 27, 53, 600928, tzinfo=utc))),
                ('news_like', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'news',
                'verbose_name_plural': 'Новости',
                'verbose_name': 'Новость',
            },
        ),
        migrations.AlterField(
            model_name='direction',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2016, 9, 12, 18, 27, 53, 597228, tzinfo=utc)),
        ),
    ]
