# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-12 18:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('landpage', '0030_auto_20160912_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments_date', models.DateTimeField(verbose_name=datetime.datetime(2016, 9, 12, 18, 31, 5, 22912, tzinfo=utc))),
                ('comments_text', models.TextField(verbose_name='Текст комментария')),
            ],
            options={
                'verbose_name_plural': 'Комментарии',
                'db_table': 'comments',
                'verbose_name': 'Комментарий',
            },
        ),
        migrations.AlterField(
            model_name='direction',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2016, 9, 12, 18, 31, 5, 15558, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2016, 9, 12, 18, 31, 5, 22126, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='comments',
            name='comments_news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landpage.News'),
        ),
    ]
