# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-12 20:56
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.contrib.auth.admin
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('landpage', '0042_auto_20160913_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comments_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2016, 9, 12, 20, 56, 12, 745271, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comments_from',
            field=models.ForeignKey(default=django.contrib.auth.admin.UserAdmin, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='direction',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2016, 9, 12, 20, 56, 12, 737962, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2016, 9, 12, 20, 56, 12, 744364, tzinfo=utc)),
        ),
    ]
